services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pass0587
      MYSQL_DATABASE: bulletBoarddb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - "3307:3306"
  tomcat:
    build: .
    container_name: my_tomcat
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

volumes:
  db-data:
networks:
  my_network:
    driver: bridge